version: '3.4'

services:
  portfolio:
    container_name: portfolio
    image: iportfolio
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile